### ISSUE TITLE
[ALPHA-2.1] Game closes when user minimizes window

### ISSUE THREAD

**Issue by andcoe** [big-ab-games/robo-instructus#108] opened 2019-01-27 16:48 UTC
After starting the game if the user clicks the window minimize button on the top right corner the game closes.

**Expected**: 
Game is minimized and the user can come back to it if needed

**Actual**:
Game closes and the user has to re-launch it

**Platform**:
Windows 10

**Comment by alexheretic** [comment] 2019-01-27 22:09
Thanks for reporting this! 

This is caused by winit generating `Resized(width=0, height=0)` events when the game is minimised in Windows but not generating them in Linux/X11. Assumptions in the code that these would be non-zero cause divide-by-zero panics that kill the compute thread. But the event isn't a problem if handled properly, so this will be fixed in the next release.

I'll also throw in some bonus pause the game & fade out music when minimised behaviour.

**Comment by alexheretic** [comment] 2019-02-08 15:30
Fixed in alpha-2.2

**Closed by alexheretic** 2019-02-08 15:30 UTC
